name: bloc_widgets
description: A new Flutter package that provides an alternative to the `BlocBuilder/Listener/Consumer/Selector` with the idea based on the `ConsumerWidget` from `riverpod` library.
version: 1.1.2
homepage: https://vgoltstein.dev/

environment:
  sdk: '>=2.18.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3